### ISSUE TITLE
Supporting other web sites for plugins or support for web sites with port(?)

### ISSUE THREAD

**Issue by DeadLyBro** [uwu/shelter#14]
When I tried with my http://ip:port/ or http://ip:port/plugin, shelter doesn't add my plugin to list and I tried with github, it worked.
(Ps: I'm sure my port is open to web, I tried to access site with my phone with VPN.)

Question is: Why Shelter doesn't support links other than github?
Edit: I came across with other links like blabla.dev and now I think its because my ip have port?
Edit2: If it's because there is a port in my IP, is there a way to fix this? I would appreciate it if you could release an update if there is one.

**Comment by xirreal** [comment]
It's most likely because of http. Switch to https to make it work, it's a web limitation and not shelter.

**Comment by DeadLyBro** [comment]
Oh, ok. Thanks.

**Comment by yellowsink** [comment]
> It's most likely because of http. Switch to https to make it work, it's a web limitation and not shelter.

CONTENT SECURITY POLICY STRIKES AGAIN!!!!!!!
