### ISSUE TITLE
Error in local plugin placeholder text

### ISSUE THREAD

**Issue by manutiedra** [uwu/shelter#15]
When adding a local plugin, the placeholder text for the code field says:

onload()

but it should say:

onLoad()

BTW, I have tried to run the plugin of the docs as a local plugin but it gives me the error:

plugin test1 errored while loading and will be unloaded: SyntaxError: Unexpected token 'const'

Can you please paste here the code for the show-username plugin that works as a local plugin?

Thank you and keep up your good work!

**Comment by yellowsink** [comment]
The getting started guide is intended to be used with Lune and will not work as a local plugin. I will fix the placeholder text.

And you can use the compiled source of the real show-username plugin from https://yellowsink.github.io/shelter-plugins/show-username/plugin.js
