### ISSUE TITLE
After installing shelter, discord opens logged out and without titlebar, and one launch later it refuses to work completely

### ISSUE THREAD

**Issue by kastentop2005** [uwu/shelter#17]
I'm using OpenAsar + BetterDiscord. Is there anythting I can do about it?

**Comment by yellowsink** [comment]
Shelter has not been tested with bd; will do testing on my end

Honestly, not sure whether to officially support other mods or not but that's a decision for later.

**Comment by yellowsink** [comment]
In my testing, installing betterdiscord does not cause any real issues, but it appears that bd does not load if the shelter injector is present.

I have no idea how to fix this, for now I'm just going to go with that running two mods alongside each other is not supported, and I do not plan to investigate how exactly to get this to work.
