### ISSUE TITLE
shelter not saving plugins

### ISSUE THREAD

**Issue by ogmicco** [uwu/shelter#3]
When I restart discord my shelter plugins disappear, where shelter is supposed to save plugins?

**Comment by ogmicco** [comment]
desktop
win 10 21h2
stable
no console errors

**Comment by ogmicco** [comment]
so the plugins should be here?
![image](https://user-images.githubusercontent.com/107354268/207938101-0043089f-8490-4ab8-b2f6-e1915bdde0eb.png)

**Comment by yellowsink** [comment]
You can access idb only via devtools. Go to application -> indexeddb -> the relevant stores

**Comment by yellowsink** [comment]
> desktop
> win 10 21h2
> stable
> no console errors

Huh. Interesting.

**Comment by ogmicco** [comment]
it started working randomly

**Comment by yellowsink** [comment]
interesting.
