### ISSUE TITLE
How can I create my own theme repo?

### ISSUE THREAD

**Issue by kitku2** [uwu/shelter#30]
So, server invites are closed and I want to make my own theme repo, how can I do that?

(enable invites for a few days please)

**Comment by yellowsink** [comment]
you need to serve a repo.json file that becomes the root URL of your repo, as demonstrated [here](https://github.com/CumcordThemes/Cumsock/blob/master/repo.json)

from there, serve a cumcord_theme.json file at the same level as your theme, as demonstrated [here](https://github.com/yellowsink/Diskai/blob/dist/cumcord_theme.json)

you can find the documentation [here](https://github.com/Cumcord/STD/blob/master/proposals/theme_manifest.md) and [here](https://github.com/Cumcord/STD/blob/master/proposals/theme_repo.md)

note that bd style metadata comments are an acceptable alternative to a separate manifest.

**Comment by kitku2** [comment]
wow, that was fast, thanks sink!
btw why are server invites disabled?

**Comment by yellowsink** [comment]
No problem! feel free to ask anything else you need

I am unfortunately not in a position to say why the server invites are disabled, apologies.

**Comment by kitku2** [comment]
can you invite me on discord? I wanna talk abt some stuff and don't want to do it here.

discowd: kitku.xyz
