### ISSUE TITLE
Copy shelter settings

### ISSUE THREAD

**Issue by Puyodead1** [uwu/shelter#32]
How can I copy shelter settings and plugins from Discord to Discord Canary?

I would have asked in the discord but it says invites are paused

**Comment by yellowsink** [comment]
this is technically possible but there is no tool available to do it as of now.
syncing the mod state via the cloud is something that has been considered too, but I have a very complicated and impractical vision for that so

**Comment by yellowsink** [comment]
closing as not an issue with the mod itself, but if I become aware of a settings transfer plugin, or make one myself, I'll let you know here.
