### ISSUE TITLE
Invites are currently paused for this server

### ISSUE THREAD

**Issue by grngxd** [uwu/shelter#36]
Discord server's invites are paused

**Comment by yellowsink** [comment]
this is not an issue. yes this is indeed true.

**Comment by grngxd** [comment]
but why? people who want to join cant, was the server raided or something? its been like this for a couple weeks now @yellowsink

**Comment by yellowsink** [comment]
I am not in a position to disclose why the server is closed, but if you can take my word for it, there is a good reason. it will remain so indefinitely.

**Comment by grngxd** [comment]
indefinitely??? damn, well at least is there somewhere else i can communicate with other shelter users/developers?

**Comment by yellowsink** [comment]
nowhere comes to mind, but if you ever need help with developing or anything my DMs are open

**Comment by grngxd** [comment]
alrighty, thank you!
