### ISSUE TITLE
Is it possible to inject into the web client for my Fosscord instance?

### ISSUE THREAD

**Issue by Hellscap3d** [uwu/shelter#4]
I've been looking around, and I can't seem to find a way to inject shelter into the web client. Its a 1 to 1 copy of discord so it should work. I tried loading it as a script, but it failed.

**Comment by Hellscap3d** [comment]
https://tech.gno.cl/

**Comment by yellowsink** [comment]
Yes, it is possible!:

![image](https://user-images.githubusercontent.com/19270622/226170089-2bb7a5c3-d708-449e-8e21-3e65fb57d28e.png)
![image](https://user-images.githubusercontent.com/19270622/226170095-aa8f34af-2acc-4b4f-a6d2-512d0eed8ef0.png)

Fosscord instance support is not currently something that is under consideration for mainline shelter as it requires changes to the extension manifest to work, feel free to fork the injector as the project is public domain, here's a diff (`git apply path_to.diff`)
```diff
diff --git a/injectors/webext/background.js b/injectors/webext/background.js
index c65382d..2f3b252 100644
--- a/injectors/webext/background.js
+++ b/injectors/webext/background.js
@@ -6,6 +6,6 @@ chrome.webRequest.onHeadersReceived.addListener(
     return { responseHeaders };
   },
 
-  { urls: ["*://*.discord.com/*", "*://discord.com/*"] },
+  { urls: ["*://*.tech.gno.cl/*", "*://tech.gno.cl/*"] },
   ["blocking", "responseHeaders"],
 );
diff --git a/injectors/webext/manifest.json b/injectors/webext/manifest.json
index 61eef9c..4f0e1d0 100644
--- a/injectors/webext/manifest.json
+++ b/injectors/webext/manifest.json
@@ -10,7 +10,7 @@
     "storage",
     "webRequest",
     "webRequestBlocking",
-    "https://discord.com/*",
+    "https://tech.gno.cl/*",
     "https://raw.githubusercontent.com/*"
   ],
 
@@ -20,7 +20,7 @@
 
   "content_scripts": [
     {
-      "matches": ["https://discord.com/*"],
+      "matches": ["https://tech.gno.cl/*"],
       "js": ["content.js"],
       "run_at": "document_start"
     }
```

**Comment by yellowsink** [comment]
You can also build it into your instance if you want - all you need to do is load the shelter dist *before any Discord code loads* - which if you control the site should be as simple as putting the script tag above the Discord scripts!

**Comment by Hellscap3d** [comment]
> You can also build it into your instance if you want - all you need to do is load the shelter dist _before any Discord code loads_ - which if you control the site should be as simple as putting the script tag above the Discord scripts!

yeah I can just inject it into the index.html (template used by all pages)
