### ISSUE TITLE
Missing Discord server link

### ISSUE THREAD

**Issue by ggtylerr** [uwu/shelter#5]
The README mentions a Discord server near the end, but I could not find a link for the life of me. And unfortunately it isn't discord.gg/uwu

**Comment by ggtylerr** [comment]
I finally found one through ARMCord's Discord. If anyone needs it, it's https://discord.gg/Awp6YgXdS6

**Comment by yellowsink** [comment]
Thanks for the heads-up, I never noticed that we don't actually really link to our Discord from anywhere!
